#!/usr/bin/env python

def indent(lines, count, ch=' '):
    padding = count * ch
    return padding + (u'\n' + padding).join(lines.split(u'\n'))

class Task:

    def __init__(self, text):
        self.text = text
        self.subtasks = []

    def add_subtask(self, task, position=-1):
        if type(task) == unicode or type(task) == str:
            task = Task(task)
        if position == -1:
            self.subtasks.append(task)
            return
        self.subtasks.insert(position, task)

class Project(Task):
    pass

class TaskFormatter:

    @staticmethod
    def format_task(task, indent):
        text = ' ' * indent + '- ' + task.text + '\n'
        for subtask in task.subtasks:
            text = text + TaskFormatter.format_task(subtask, indent + 2)
        return text

    @staticmethod
    def format(task):
        return TaskFormatter.format_task(task, 0)        

    
task = Project("main task")
task.add_subtask(u"subtask 1")
task.add_subtask(u"subtask 2", 0)
task.subtasks[0].add_subtask(u"aaaa")
task.subtasks[0].add_subtask(u"bbb")
print TaskFormatter.format(task)

