#!/usr/bin/env python

def indent(lines, count, ch=' '):
    padding = count * ch
    return padding + (u'\n' + padding).join(lines.split(u'\n'))

class Task:
    def __init__(self, text):
        self.text = text
        self.subtasks = []
        self.parent = None
    def add_subtask(self, task, position=-1):
        if position == -1:
            self.subtasks.append(task)
            return
        self.subtasks.insert(position, task)
    def get_text(self, with_subtasks=False):
        if not with_subtasks:
            return self.text
        text = u''
        for i, task in enumerate(self.subtasks):
            text = text + task.get_text(with_subtasks=True).strip() + u'\n'
        text = self.text + u'\n' + indent(text, 2)
        return text

task = Task(u"main task")
task.add_subtask(Task(u"subtask 1"))
task.add_subtask(Task(u"subtask 2"))
print task.get_text()
print task.get_text(with_subtasks=True)

